apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  labels:
    nerc.mghpcc.org/sync-policy: common
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-on-nerc/nerc-ocp-config.git
    targetRevision: HEAD
    path: loki/overlays/nerc-ocp-obs
  destination:
    name: nerc-ocp-obs
    namespace: openshift-operators-redhat
