apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-on-nerc/nerc-ocp-config.git
    targetRevision: HEAD
    path: external-secrets/overlays/nerc-ocp-infra
  destination:
    name: nerc-ocp-infra
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
