apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-keycloak-proxy
  labels:
    nerc.mghpcc.org/sync-policy: common
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-on-nerc/nerc-ocp-config.git
    targetRevision: HEAD
    path: prom-keycloak-proxy/overlays/nerc-ocp-obs
  destination:
    name: nerc-ocp-obs
    namespace: prom-keycloak-proxy
