apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../lib/cluster-scope
  - ../lib/nfd-operator
  - ../lib/nvidia-gpu-operator
  - ../lib/logging
  - ../lib/virt
  - ../lib/nfs
  - ../lib/csi-driver-nfs
  - ../lib/autopilot
  - dex
  - minio

nameSuffix: -test

patches:
  - target:
      kind: Application
      labelSelector: "nerc.mghpcc.org/sync-policy=common"
    patch: |
      - op: add
        path: /spec/syncPolicy
        value:
          automated:
            selfHeal: true
          syncOptions:
            - ApplyOutOfSyncOnly=true

  - target:
      kind: Application
    patch: |
      - op: replace
        path: /spec/destination/name
        value: nerc-ocp-test

  - target:
      kind: Application
      name: cluster-scope
    patch: |
      - op: replace
        path: /spec/source/path
        value: cluster-scope/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: nfd-operator
    patch: |
      - op: replace
        path: /spec/source/path
        value: nfd-operator/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: nvidia-gpu-operator
    patch: |
      - op: replace
        path: /spec/source/path
        value: nvidia-gpu-operator/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: logging
    patch: |
      - op: replace
        path: /spec/source/path
        value: logging/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: virt
    patch: |
      - op: replace
        path: /spec/source/path
        value: virt/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: nfs
    patch: |
      - op: replace
        path: /spec/source/path
        value: nfs/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: csi-driver-nfs
    patch: |
      - op: replace
        path: /spec/source/path
        value: csi-driver-nfs/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: autopilot
    patch: |
      - op: replace
        path: /spec/source/path
        value: autopilot/overlays/nerc-ocp-test
