apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../lib/cluster-scope
  - ../lib/nfd-operator
  - ../lib/nvidia-gpu-operator
  - ../lib/logging
  - curator
  - koku-metrics-operator

nameSuffix: -test

patches:
  - target:
      kind: Application
      labelSelector: "nerc.mghpcc.org/sync-policy=common"
    patch: |
      - op: add
        path: /spec/syncPolicy
        value:
          automated:
            selfHeal: true
          syncOptions:
            - ApplyOutOfSyncOnly=true

  - target:
      kind: Application
    patch: |
      - op: replace
        path: /spec/destination/name
        value: nerc-ocp-test

  - target:
      kind: Application
      name: cluster-scope
    patch: |
      - op: replace
        path: /spec/source/path
        value: cluster-scope/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: nfd-operator
    patch: |
      - op: replace
        path: /spec/source/path
        value: nfd-operator/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: nvidia-gpu-operator
    patch: |
      - op: replace
        path: /spec/source/path
        value: nvidia-gpu-operator/overlays/nerc-ocp-test

  - target:
      kind: Application
      name: logging
    patch: |
      - op: replace
        path: /spec/source/path
        value: logging/overlays/nerc-ocp-test
