apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koku-metrics-operator
  labels:
    nerc.mghpcc.org/sync-policy: common
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-on-nerc/nerc-ocp-config.git
    targetRevision: HEAD
    path: koku-metrics-operator/overlays/nerc-ocp-edu
  destination:
    name: nerc-ocp-edu
    namespace: koku-metrics-operator
