apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xdmod
spec:
  project: default
  source:
    repoURL: https://github.com/CCI-MOC/xdmod-cntr.git
    targetRevision: HEAD
    path: k8s/overlays/nerc-ocp-infra
  destination:
    name: nerc-ocp-infra
    namespace: xdmod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
    retry:
      limit: -1
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 30min
