apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: disable-aslr
  labels:
    nerc.mghpcc.org/sync-policy: common
spec:
  destination:
    name: nerc-ocp-edu
    namespace: rhods-notebooks
  project: default
  source:
    repoURL: https://github.com/OCP-on-NERC/disable-aslr-nerc.git
    path: disable-aslr/overlays/nerc-ocp-edu
    targetRevision: HEAD
